name: Deploying To Firebase Hosting

on:
  push:
    branches:
      - master

jobs:
  firebase-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Installing Dependencies
        run: npm install

      - name: Building The Project
        run: npm run build:prod

      - name: Installing Firebase Tools
        run: npm install -g firebase-tools

      - name: Deploying To Firebase Hosting
        run: firebase deploy --only hosting --project mp3-converter-hy --token="${{ secrets.FIREBASE_TOKEN }}"
